function reservation (text: string) {
    host.sayText("" + text)
    pause(2000)
    person.sayText(game.askForString("Name", 10))
    pause(2000)
    host.sayText("Okay follow me")
}
// Don't forget to comment your code as you work!
let person: Sprite = null
let host: Sprite = null
host = sprites.create(img`
    ...............
    ...............
    ...............
    ...............
    .....eeeee.....
    .....eddde.....
    .....dfdfd.....
    .....ddddd.....
    .....ddddd.....
    ......ddd......
    ......ddd......
    ...1111f1111...
    ...dd11f11dd...
    ...dd11f11dd...
    ...dd11111dd...
    .....11111.....
    .....fffff.....
    .....fffff.....
    .....ff.ff.....
    .....ff.ff.....
    .....ff.ff.....
    .....ff.ff.....
    `, SpriteKind.Player)
person = sprites.create(img`
    . . . . . f f 4 4 f f . . . . . 
    . . . . f 5 4 5 5 4 5 f . . . . 
    . . . f e 4 5 5 5 5 4 e f . . . 
    . . f b 3 e 4 4 4 4 e 3 b f . . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 e b 3 e e 3 b e 3 3 f . 
    . f 3 3 f f e e e e f f 3 3 f . 
    . f b b f b f e e f b f b b f . 
    . f b b e 1 f 4 4 f 1 e b b f . 
    f f b b f 4 4 4 4 4 4 f b b f f 
    f b b f f f e e e e f f f b b f 
    . f e e f b d d d d b f e e f . 
    . . e 4 c d d d d d d c 4 e . . 
    . . e f b d b d b d b b f e . . 
    . . . f f 1 d 1 d 1 d f f . . . 
    . . . . . f f b b f f . . . . . 
    `, SpriteKind.Player)
person.setPosition(80, 101)
reservation("What is the name for the order?")
